ARG BASE_IMAGE=fedora:44@sha256:43b29f65a41eb9c35e1cd5323e3bdf3b655c2357a9f4f1ff2f9c2798e5045d80
FROM ${BASE_IMAGE}

ARG RPM_PLATFORM
ARG PG_CONFIG_PATH

ENV PKG_CONFIG_PATH=/usr/local/lib64/pkgconfig:/usr/local/lib/pkgconfig

WORKDIR /opt/pg-oauth-validator
COPY scripts/ci/install-rpm-dependencies.sh ./scripts/ci/install-rpm-dependencies.sh
RUN ./scripts/ci/install-rpm-dependencies.sh "$RPM_PLATFORM" \
    && dnf clean all
COPY scripts/ci/install-jansson.sh scripts/ci/install-libjwt.sh ./scripts/ci/
RUN ./scripts/ci/install-jansson.sh \
    && ./scripts/ci/install-libjwt.sh \
    && dnf clean all
COPY tools/dev/run-tests.sh ./tools/dev/run-tests.sh

ENV PG_MAJOR=18
ENV PG_CONFIG_PATH=${PG_CONFIG_PATH}
ENV LD_LIBRARY_PATH=/usr/local/lib
WORKDIR /workspace
ENTRYPOINT ["/bin/sh", "/opt/pg-oauth-validator/tools/dev/run-tests.sh"]
