#!/bin/sh

set -eu

# Records the reviewed checksums of a published tag's source tarball, for
# downstream distribution packagers whose build systems pin a source URL
# together with a digest.
#
# The tarball is generated by the Git forge, not by this project, so it is
# fetched and then checked against a local `git archive` of the same tag. That
# comparison is the point: it proves the published tarball contains exactly the
# signed tag's tree, and that the digest below belongs to that tree rather than
# to whatever the forge happened to serve.
#
# Run this only after the annotated, signed tag has been pushed. Publish the
# output verbatim in the release notes.

usage()
{
	echo "usage: $0 TAG [OUTPUT_FILE]" >&2
	exit 2
}

test "$#" -ge 1 && test "$#" -le 2 || usage

tag=$1
output=${2-}

case "$tag" in
	v[0-9]*) ;;
	*)
		echo "error: tag must be spelled v<version>, for example v0.1.0" >&2
		exit 2
		;;
esac

repository=${SOURCE_REPOSITORY:-proddata/pg_oauth_validator}
archive_url="https://github.com/$repository/archive/refs/tags/$tag.tar.gz"

script_dir=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)
source_dir=$(CDPATH= cd -- "$script_dir/../.." && pwd)

git -C "$source_dir" cat-file -e "$tag^{commit}" 2>/dev/null || {
	echo "error: $tag is not a tag in this repository" >&2
	exit 1
}

# A release tag must be annotated and signed. Refuse to publish checksums for a
# tag that does not meet the policy in docs/release-readiness.md.
test "$(git -C "$source_dir" cat-file -t "$tag")" = tag || {
	echo "error: $tag is a lightweight tag; release tags must be annotated" >&2
	exit 1
}
git -C "$source_dir" verify-tag "$tag" >/dev/null 2>&1 || {
	echo "error: the signature on $tag does not verify" >&2
	exit 1
}

if command -v sha256sum >/dev/null 2>&1; then
	digest() { sha256sum "$1" | awk '{print $1}'; }
	digest512() { sha512sum "$1" | awk '{print $1}'; }
else
	digest() { shasum -a 256 "$1" | awk '{print $1}'; }
	digest512() { shasum -a 512 "$1" | awk '{print $1}'; }
fi

work_dir=$(mktemp -d "${TMPDIR:-/tmp}/pg-oauth-source.XXXXXX")
trap 'rm -rf "$work_dir"' EXIT HUP INT TERM

published=$work_dir/published.tar.gz
curl --fail --location --proto '=https' --tlsv1.2 \
	--output "$published" "$archive_url"

# Compare trees, not bytes: the forge's tarball is not byte-reproducible, but
# its content must match the tag exactly.
mkdir -p "$work_dir/published" "$work_dir/local"
tar --extract --gzip --file "$published" \
	--directory "$work_dir/published" --strip-components=1
git -C "$source_dir" archive --format=tar "$tag" |
	tar --extract --file - --directory "$work_dir/local"

if ! diff --recursive --brief "$work_dir/local" "$work_dir/published"; then
	echo "error: the published tarball does not match the tree of $tag" >&2
	exit 1
fi

{
	echo "tag: $tag"
	echo "commit: $(git -C "$source_dir" rev-parse "$tag^{commit}")"
	echo "source-url: $archive_url"
	echo "sha256: $(digest "$published")"
	echo "sha512: $(digest512 "$published")"
	echo "tree-matches-tag: yes"
} | if test -n "$output"; then tee "$output"; else cat; fi
