#ifndef PG_OAUTH_VALIDATOR_ALGORITHMS_H
#define PG_OAUTH_VALIDATOR_ALGORITHMS_H

#include <stdint.h>

#define PG_OAUTH_ALGORITHM_RS256 (UINT32_C(1) << 0)
#define PG_OAUTH_ALGORITHM_ES256 (UINT32_C(1) << 1)

#endif							/* PG_OAUTH_VALIDATOR_ALGORITHMS_H */
